version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    env_file:
      - .env
    ports:
    - "5432:5432"
    volumes:
    - timescaledb_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
    - "1883:1883"
    volumes:
    - mqtt_data:/mosquitto/data
    - mqtt_log:/mosquitto/log
    - ./mosquitto/config:/mosquitto/config
    env_file:
      - .env

  webserver:
    build: ./WebServer
    container_name: webserver
    ports:
    - "5000:5000"
    env_file:
      - .env

volumes:
  timescaledb_data:
  mqtt_data:
  mqtt_log:
