version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: smart_mailbox
    ports:
    - "5432:5432"
    volumes:
    - timescaledb_data:/var/lib/postgresql/data
    - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
    - "1883:1883"
    volumes:
    - mqtt_data:/mosquitto/data
    - mqtt_log:/mosquitto/log
    - ./mosquitto/config:/mosquitto/config
    environment:
    - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
    - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}

volumes:
  timescaledb_data:
  mqtt_data:
  mqtt_log:
