# Configuration file for WebServer
flask:
  secret_key: my_super_secret_key
  debug: True

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: web_server
  username: user
  password: password

database:
  host: 127.0.0.1
  port: 5432
  name: smart_mailbox
  user: user
  password: password

email:
  smtp_server: smtp.example.com
  port: 587
  username: your_email_username
  password: your_email_password
  from_address: no-reply@example.com

logging:
  level: INFO
  file: /var/log/controlserver.log
