# Configuration file for WebServer
flask:
  secret_key: my_super_secret_key
  debug: False

mqtt:
  broker: mqtt
  port: 1883
  client_id: web_server
  username: your_username
  password: your_password

database:
  host: timescaledb
  port: 5432
  name: smart_mailbox
  user: your_username
  password: your_password

email:
  smtp_server: mail.gmx.net
  port: 587
  username: nils-baxheinrich@gmx.de
  password: h4be8zDTGiwgNZ86U6
  from_address: nils-baxheinrich@gmx.de

logging:
  level: INFO
  file: /var/log/controlserver.log
