# Configuration file for WebServer
flask:
  secret_key: my_super_secret_key

mqtt:
  broker: localhost
  port: 1883
  client_id: web_server_client
  topic: mailbox/#
  qos: 1
  keep_alive: 60
  clean_session: true
  username: mqtt_user
  password: mqtt_password

database:
  uri: sqlite:///C:/Users/elina/Desktop/HSBI/5. Semester/IoT & Vernetzung/Project/VIOT-Project/WebServer/database/data.db

