# Configuration file for WebServer
flask:
  secret_key: my_super_secret_key
  debug: False

mqtt:
  broker: mqtt
  port: 1883
  client_id: web_server
  username: your_username
  password: your_password

database:
  host: timescaledb
  port: 5432
  name: smart_mailbox
  user: your_username
  password: your_password

email:
  smtp_server: smtp.example.com
  port: 587
  username: your_email_username
  password: your_email_password
  from_address: no-reply@example.com

logging:
  level: INFO
  file: /var/log/controlserver.log
